/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/root'
import { Route as signupImport } from './routes/signup'
import { Route as loginImport } from './routes/login'
import { Route as mainLayoutImport } from './routes/main-layout'
import { Route as homeImport } from './routes/home'
import { Route as appSeekImport } from './routes/app-seek'
import { Route as appOffersImport } from './routes/app-offers'
import { Route as appIndexImport } from './routes/app-index'

// Create/Update Routes

const signupRoute = signupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const loginRoute = loginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const mainLayoutRoute = mainLayoutImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const homeRoute = homeImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const appSeekRoute = appSeekImport.update({
  id: '/seek',
  path: '/seek',
  getParentRoute: () => mainLayoutRoute,
} as any)

const appOffersRoute = appOffersImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => mainLayoutRoute,
} as any)

const appIndexRoute = appIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof mainLayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof signupImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof appIndexImport
      parentRoute: typeof mainLayoutImport
    }
    '/app/offers': {
      id: '/app/offers'
      path: '/offers'
      fullPath: '/app/offers'
      preLoaderRoute: typeof appOffersImport
      parentRoute: typeof mainLayoutImport
    }
    '/app/seek': {
      id: '/app/seek'
      path: '/seek'
      fullPath: '/app/seek'
      preLoaderRoute: typeof appSeekImport
      parentRoute: typeof mainLayoutImport
    }
  }
}

// Create and export the route tree

interface mainLayoutRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appOffersRoute: typeof appOffersRoute
  appSeekRoute: typeof appSeekRoute
}

const mainLayoutRouteChildren: mainLayoutRouteChildren = {
  appIndexRoute: appIndexRoute,
  appOffersRoute: appOffersRoute,
  appSeekRoute: appSeekRoute,
}

const mainLayoutRouteWithChildren = mainLayoutRoute._addFileChildren(
  mainLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof homeRoute
  '/app': typeof mainLayoutRouteWithChildren
  '/login': typeof loginRoute
  '/signup': typeof signupRoute
  '/app/': typeof appIndexRoute
  '/app/offers': typeof appOffersRoute
  '/app/seek': typeof appSeekRoute
}

export interface FileRoutesByTo {
  '/': typeof homeRoute
  '/login': typeof loginRoute
  '/signup': typeof signupRoute
  '/app': typeof appIndexRoute
  '/app/offers': typeof appOffersRoute
  '/app/seek': typeof appSeekRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof homeRoute
  '/app': typeof mainLayoutRouteWithChildren
  '/login': typeof loginRoute
  '/signup': typeof signupRoute
  '/app/': typeof appIndexRoute
  '/app/offers': typeof appOffersRoute
  '/app/seek': typeof appSeekRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/'
    | '/app/offers'
    | '/app/seek'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/app' | '/app/offers' | '/app/seek'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/'
    | '/app/offers'
    | '/app/seek'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  homeRoute: typeof homeRoute
  mainLayoutRoute: typeof mainLayoutRouteWithChildren
  loginRoute: typeof loginRoute
  signupRoute: typeof signupRoute
}

const rootRouteChildren: RootRouteChildren = {
  homeRoute: homeRoute,
  mainLayoutRoute: mainLayoutRouteWithChildren,
  loginRoute: loginRoute,
  signupRoute: signupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "root.tsx",
      "children": [
        "/",
        "/app",
        "/login",
        "/signup"
      ]
    },
    "/": {
      "filePath": "home.tsx"
    },
    "/app": {
      "filePath": "main-layout.tsx",
      "children": [
        "/app/",
        "/app/offers",
        "/app/seek"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/app/": {
      "filePath": "app-index.tsx",
      "parent": "/app"
    },
    "/app/offers": {
      "filePath": "app-offers.tsx",
      "parent": "/app"
    },
    "/app/seek": {
      "filePath": "app-seek.tsx",
      "parent": "/app"
    }
  }
}
ROUTE_MANIFEST_END */
