import { FeedDisplay, FeedDisplayMinimal } from "@app/components/seek";
import {
	Sheet,
	SheetContent,
	SheetDescription,
	SheetHeader,
	SheetTitle,
	SheetTrigger,
} from "@app/components/ui/sheet";
import NumberFlow from "@number-flow/react";
import { z } from "zod";

import {
	consumptionSummaryAtom,
	feedAtom,
	handleNewFeedEventAtom,
	initializeSocketAtom,
	mainAgentStatusAtom,
	messageContainerRefAtom,
	offersAtom,
	routerOutputAtom,
	sendMessageAtom,
	statusAtom,
	userInteractionAtom,
} from "@app/atoms/seek";

import {
	UserInteractionInputSchema,
	UserInteractionSelectInputSchema,
} from "@agent/agents/schemas";
import { Button } from "@app/components/ui/button";
import { Checkbox } from "@app/components/ui/checkbox";
import {
	Dialog,
	DialogContent,
	DialogHeader,
	DialogTitle,
} from "@app/components/ui/dialog";
import { Textarea } from "@app/components/ui/textarea";
import { SETTINGS } from "@app/settings";
import { createFileRoute } from "@tanstack/react-router";
import { useAtom, useAtomValue, useSetAtom } from "jotai";
import { ArrowUp } from "lucide-react";
import Markdown from "markdown-to-jsx";
import { type ReactNode, useEffect, useRef } from "react";
import { BeatLoader } from "react-spinners";

export const Route = createFileRoute("/app/seek")({
	component: SeekPage,
});

function SeekPage() {
	const ref = useRef<HTMLDivElement>(null);
	const feed = useAtomValue(feedAtom);
	const handleNewFeedEvent = useSetAtom(handleNewFeedEventAtom);
	const initializeSocket = useSetAtom(initializeSocketAtom);
	const sendMessage = useSetAtom(sendMessageAtom);
	const mainAgentStatus = useAtomValue(mainAgentStatusAtom);
	const setContainerRef = useSetAtom(messageContainerRefAtom);

	useEffect(() => {
		setContainerRef(ref);

		const close = initializeSocket(SETTINGS.API.WEBSOCKET_URL);
		return () => {
			close();
		};
	}, [initializeSocket, setContainerRef]);

	const onSubmit = (e: React.FormEvent<HTMLFormElement>) => {
		e.preventDefault();
		const formData = new FormData(e.currentTarget);
		const message = formData.get("user-message") as string;
		sendMessage({
			type: "user.query",
			message,
		});

		handleNewFeedEvent({
			event: "user.query",
			data: {
				query: message,
			},
		});
		e.currentTarget.reset();
	};

	return (
		<div className="flex flex-col gap-4 w-full h-full">
			<ConsumptionDisplay />

			<UserInteractionDialog />

			<div
				className="flex flex-col gap-2 overflow-y-auto h-full w-full"
				ref={ref}
			>
				{mainAgentStatus === "idle" && (
					<div className="m-auto">
						<Tutorial />
					</div>
				)}
				{mainAgentStatus !== "idle" && <FeedDisplayMinimal feed={feed} />}
				<StatusDisplay />
			</div>

			{mainAgentStatus === "idle" && (
				<div className="mt-auto ">
					<form
						className="relative w-full max-w-[700px] mx-auto"
						onSubmit={onSubmit}
					>
						<Textarea name="user-message" className="w-full h-[100px]" />
						<Button
							type="submit"
							className="absolute bottom-2 right-2"
							size="icon"
						>
							<ArrowUp />
						</Button>
					</form>
				</div>
			)}
		</div>
	);
}

function WebsocketStatusDisplay() {
	const connectionStatus = useAtomValue(statusAtom);
	return (
		<div className="flex items-center gap-2">
			{connectionStatus === "connected" && (
				<>
					agents connected:
					<div className="size-[16px] bg-emerald-500 rounded-full animate-pulse" />
				</>
			)}
			{connectionStatus === "disconnected" && (
				<>
					disconnected
					<div className="size-[16px] bg-red-500 rounded-full " />
				</>
			)}
		</div>
	);
}

function AssetsDisplay() {
	const offers = useAtomValue(offersAtom);
	const coverLetters = useAtomValue(routerOutputAtom);

	const numberOfAssets = offers.length;
	+coverLetters.length;

	if (numberOfAssets === 0) {
		return null;
	}

	return (
		<Sheet>
			<SheetTrigger>
				<div className="relative cursor-pointer">
					Assets
					<div className="absolute -top-3 -right-3 size-[24px] text-white bg-red-500 rounded-full text-[12px] p-1 flex justify-center items-center scale-75">
						<div>{numberOfAssets}</div>
					</div>
				</div>
			</SheetTrigger>
			<SheetContent className="min-w-[800px] p-8 overflow-y-auto">
				<SheetHeader>
					<SheetTitle>Assets Created By The Aents</SheetTitle>
					<SheetDescription>
						This is the list of assets created by the agents, you will find job
						offers as well as cover letters generated by the agents as they are
						working on your query.
					</SheetDescription>
				</SheetHeader>

				<div className="flex flex-col gap-4 ">
					<div className="text-2xl">Job Offers</div>
					<div className="h-[500px] overflow-y-auto flex flex-col gap-4 p-4 bg-slate-100 rounded-md">
						{offers.map((offer) => (
							<div
								key={JSON.stringify(offer)}
								className="p-4 rounded-lg border bg-white"
							>
								<div className="font-semibold">{offer.title}</div>
								<a href={offer.url} className="underline line-clamp-1 text-sm">
									{offer.url}
								</a>
								<div className="text-sm line-clamp-3 mt-4 opacity-70">
									h{offer.description}
								</div>
							</div>
						))}
					</div>
				</div>

				<div className="flex flex-col gap-4 ">
					<div className="text-2xl">Cover Letters</div>
					<div className="h-[500px] overflow-y-auto flex flex-col gap-4 ">
						{coverLetters.map((letter) => (
							<div
								key={JSON.stringify(letter)}
								className="p-4 rounded-lg border "
							>
								<div className="font-semibold">Cover letter {letter.id}</div>
								<div className="text-sm line-clamp-3 mt-4 opacity-70">
									<Markdown>{letter.content}</Markdown>
								</div>
							</div>
						))}
					</div>
				</div>
			</SheetContent>
		</Sheet>
	);
}

function ConsumptionDisplay() {
	const total = useAtomValue(consumptionSummaryAtom);
	const mainAgentStatus = useAtomValue(mainAgentStatusAtom);
	const money =
		(0.4 * total.inputTokens) / 1_000_000 +
		(1.6 * total.outputTokens) / 1_000_000;

	const collapseAll = () => {
		// find all element with data-state="open" withtin the div id container recursively and toggle them to closed
		const elements = document.querySelectorAll(
			'[data-state="open"]',
		) as NodeListOf<HTMLElement>;
		console.log(elements.length);
		for (const element of elements) {
			element.setAttribute("data-state", "closed");
		}
		console.log("Collapse all");
	};

	return (
		<div className="text-xs text-gray-500 flex gap-4 shadow-md p-2 rounded-md items-center">
			{mainAgentStatus !== "idle" && (
				<>
					<div>Model: GPT 4.1 Mini</div>
					{/* <div>
						Input tokens: <NumberFlow value={total.inputTokens} />
					</div>
					<div>
						Output tokens: <NumberFlow value={total.outputTokens} />
					</div> */}
					<div>
						Total tokens: <NumberFlow value={total.totalTokens} />
					</div>
					<div>
						Cost: $<NumberFlow value={money} />
					</div>
				</>
			)}
			<div className="flex ml-auto w-max gap-4">
				{
					// <p onClick={() => collapseAll()}>Collapse all</p>
				}
				<AssetsDisplay />
				<WebsocketStatusDisplay />
			</div>
		</div>
	);
}

function UserInteractionDialog() {
	const [userInteractionQuery, setUserInteractionQuery] =
		useAtom(userInteractionAtom);

	const sendMessage = useSetAtom(sendMessageAtom);

	const parsedQuery = userInteractionQuery
		? z
				.union([UserInteractionSelectInputSchema, UserInteractionInputSchema])
				.parse(JSON.parse(userInteractionQuery))
		: null;

	if (!parsedQuery) {
		return null;
	}

	function hasChoices(
		query: any,
	): query is { prompt: string; choices: { value: string; label: string }[] } {
		return "choices" in query;
	}

	const onSubmit = (e: React.FormEvent<HTMLFormElement>) => {
		e.preventDefault();
		const formData = new FormData(e.currentTarget);

		// For checkbox array values
		if (hasChoices(parsedQuery)) {
			const selectedChoices = formData
				.getAll("user-choices[]")
				.map((value) => String(value));

			console.log("Selected choices:", selectedChoices);
			sendMessage({
				type: "user.interaction.response",
				message: JSON.stringify(selectedChoices),
			});
		} else {
			const message = formData.get("user-message") as string;

			console.log("User message:", message);
			sendMessage({
				type: "user.interaction.response",
				message,
			});
		}

		setUserInteractionQuery(null);
	};

	let form: ReactNode = undefined;
	if (hasChoices(parsedQuery)) {
		form = (
			<form className="relative" onSubmit={onSubmit}>
				{parsedQuery.choices.map((choice) => (
					<div key={choice.value} className="flex gap-4 items-center">
						<Checkbox
							id={choice.value}
							name="user-choices[]"
							className="size-5"
							value={choice.value}
						/>
						<label htmlFor={choice.value}>{choice.label}</label>
					</div>
				))}
				<Button type="submit" className="absolute bottom-2 right-2" size="icon">
					<ArrowUp />
				</Button>
			</form>
		);
	} else {
		form = (
			<form className="relative" onSubmit={onSubmit}>
				<Textarea name="user-message" className="w-full h-[100px]" />
				<Button type="submit" className="absolute bottom-2 right-2" size="icon">
					<ArrowUp />
				</Button>
			</form>
		);
	}

	return (
		<Dialog open={!!parsedQuery}>
			<DialogContent className="min-w-[800px] max-w-[800px]">
				<DialogHeader>
					<DialogTitle>The agent need yggour input</DialogTitle>
				</DialogHeader>

				<div className="prose">
					<Markdown>{parsedQuery.prompt}</Markdown>
				</div>
				{form}
			</DialogContent>
		</Dialog>
	);
}

function Tutorial() {
	const description = `
Our multi agent system is designs to help you find your dream job.

The router agent use different tools and agents to complete the tedious search for you and will create a personalized cover letter tailored specifcally for each job offer.

1. You ask a question like: "Find me AI Engineers jobs in Geneva"
2. The router agent first use the offer finder agent to find job offers that match your query
3. Then it will ask you to select the offers you are most interested in
5. The offer enricher agent will then scrape the job offer page, company page, and company linkedin profile to extract important information to create the cover letter
6. For each job offer, the router agent will give you a cover letter that you can use to apply for the job
`;

	return (
		<div className="space-y-8">
			<div className="text-center text-2xl font-bold">
				Let our AI agents find your dream job for you!
			</div>

			<div
				id="description prose"
				className="prose mx-auto bg-slate-100 p-4 rounded-md shadow-md"
			>
				<Markdown>{description}</Markdown>
			</div>
			<div className="grid grid-cols-2 gap-8">
				<ExamplePromptButton>
					Find me AI Engineers jobs in Geneva
				</ExamplePromptButton>

				<ExamplePromptButton>Find me remote jobs in AI</ExamplePromptButton>

				<ExamplePromptButton>
					Find me software engineering jobs in Switzerland
				</ExamplePromptButton>

				<ExamplePromptButton>
					Find me data engineering jobs in France
				</ExamplePromptButton>
			</div>
		</div>
	);
}

function ExamplePromptButton({
	children,
}: {
	children: ReactNode;
}) {
	const handleNewFeedEvent = useSetAtom(handleNewFeedEventAtom);
	const sendMessage = useSetAtom(sendMessageAtom);

	const onClick = () => {
		handleNewFeedEvent({
			event: "user.query",
			data: {
				query: children as string,
			},
		});
		sendMessage({
			type: "user.query",
			message: children as string,
		});
	};

	return (
		<button type="button" className="cursor-pointer" onClick={onClick}>
			<div className="p-8 rounded-md bg-slate-100 shadow-md">{children}</div>
		</button>
	);
}

function StatusDisplay() {
	const status = useAtomValue(mainAgentStatusAtom);

	switch (status) {
		case "running":
			return (
				<div className="flex items-center gap-2 my-8">
					Main agent running{" "}
					<BeatLoader size={12} color="var(--color-emerald-500)" />
				</div>
			);
		case "idle":
			return null;
		case "done":
			return null;
	}
}
